# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MonsterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fightable', models.BooleanField(default=True)),
                ('xp', models.IntegerField(blank=True, null=True)),
                ('hit_points', models.IntegerField(blank=True, null=True)),
                ('size', models.SmallIntegerField(choices=[(10, 'tiny'), (20, 'small'), (30, 'medium'), (40, 'large'), (50, 'huge')])),
                ('common_drops', models.ManyToManyField(related_name='drops_common', to='items.Item')),
                ('rare_drops', models.ManyToManyField(related_name='drops_rare', to='items.Item')),
                ('uncommon_drops', models.ManyToManyField(related_name='drops_uncommon', to='items.Item')),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='monster_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npcs.MonsterType'),
        ),
    ]
